# Generated by Django 5.2.3 on 2025-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='utilisateur',
            new_name='vendeur',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='utilisateur',
            new_name='vendeur',
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('vendeur', 'Commerçant')], max_length=20),
        ),
    ]
