# Generated by Django 5.2.3 on 2025-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('vendeur', 'Commercant')], default='vendeur', max_length=20),
        ),
    ]
