# Generated by Django 5.2.3 on 2025-06-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('vendeur', 'Commercant')], max_length=20),
        ),
    ]
